services:
  rotc:
    container_name: rotc
    image: php:8.2-fpm
    volumes:
      - ./app:/var/www/html/app
    ports:
      - 1212:8000
      - 5173:5173
    build: 
      dockerfile: Dockerfile
    depends_on:
      - rotc_db
  rotc_db:
    container_name: rotc_db
    image: mysql:9.0
    ports:
      - 1414:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rotc_db
    volumes:
      - ./db:/var/lib/mysql
